apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: akilan/node-app:v1
        name: node-app
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: API_KEY
          value: "secret123"
        - name: API_URL
          value: "http://emp-app:3000"
